name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: cosign
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Install cosign
        uses: sigstore/cosign-installer@v3.0.1

      -
        name: Extract tag nginx version tag
        id: vars
        run: echo ::set-output name=nginx_version::$(cat Dockerfile| grep "NGINX_VERSION" | head -1 | awk -F= '{ print $2 }' | sed 's/[",]//g')

      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ghcr.io/bratteng/nginx
            bratteng/nginx
          flavor: |
            latest=true
          tags: |
            type=raw,value=mainline
            type=semver,pattern={{version}},value=${{ steps.vars.outputs.nginx_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.vars.outputs.nginx_version }}
            type=semver,pattern={{major}},value=${{ steps.vars.outputs.nginx_version }}

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.4.1
        with:
          install: true

      -
        name: Cache Docker layers
        uses: actions/cache@v3.2.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
            ${{ runner.os }}-
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      -
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      -
        name: Sign image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key
          cosign sign --key cosign.key ghcr.io/bratteng/nginx@${{ steps.build.outputs.digest }}
          cosign sign --key cosign.key bratteng/nginx@${{ steps.build.outputs.digest }}

      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
